### ISSUE TITLE
Add rom suggestions to README

### ISSUE THREAD

**Issue by kbrock** [colby-swandale/waterfoul#2]
Any pointers to roms?

I did find a few at http://gbdev.gg8.se/files/jsGB/tests/ but wasn't sure if there was a good source of roms.

Also, is there a particular phrase I should look for to test these roms?
I'm just learning that there is a GB color, GB advanced, among others.

Thanks

**Comment by colby-swandale** [comment]
Hi @kbrock,
The page you linked are a set of ROMs that test the accuracy of a Gameboy emulator (i use those personally as well). They're compatible with the original Gameboy, GB Color and GB Pocket and i recommend using them for testing.

I can't link anywhere specific to actual GB game ROMs due to copyright but you want to look for ROMs for the Gameboy only. ROMs for the Gameboy Color & Advanced are not compatible with this emulator.

**Comment by kbrock** [comment]
Perfect. Thanks.

Yes, I linked to that page in particular because I didn't want to enter into the copyrighted world.
